---
- name: restart_nginx
  shell: |
    docker stop nginx || true
    docker rm nginx || true
  ignore_errors: true

- name: Run new Nginx container
  shell: >
    docker run -d --name nginx -p {{ nginx_port }}:80 -v /tmp/nginx.conf:/etc/nginx/conf.d/default.conf --restart always nginx
