- name: Manage Apache2 installation and service usage ansible-playbook manage_apache.yml -e "action=install"
  hosts: all
  become: yes
  vars:
    action: "install"  # Default action, can be overridden with --extra-vars
    # block - when clause makes kind of proc which is called when var (action) has some value
  tasks:
    - block:
        - name: Install Apache2
          apt:
            name: apache2
            state: latest
            update_cache: yes
      when: action == "install"

    - block:
        - name: Start Apache2 service
          service:
            name: apache2
            state: started
      when: action == "start"

    - block:
        - name: Restart serv
          service: name=apache2 state=restarted
      when: action == "restart"

    - block:
        - name: Stop Apache2 service
          service:
            name: apache2
            state: stopped
      when: action == "stop"
    # if var is not in list of values of sense
    - block:
        - name: Debug invalid action
          debug:
            msg: "Invalid action '{{ action }}'. Use 'install', 'start', 'restart' or 'stop'."
      when: action not in ["install", "start", "stop","restart"]
